const data = [
	// "Computer" Category
	{
		name: 'Process',
		title: 'Process',
		description: 'Process set of data.',
		icon: 'gear',
		icon_color: 'grey-bleed',
		id: 'process',
		footer: null,
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
		name: 'Stop',
		title: 'Stop',
		description: 'Cease an operation.',
		icon: 'stop',
		icon_color: 'red-bleed',
		id: 'stop',
		footer: 'This can be used to represent processes.',
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
		name: 'True',
		title: 'True',
		description: 'An output representing true.',
		icon: 'check',
		icon_color: 'green-bleed',
		id: 'true',
		footer: 'This can be used to represent outputs.',
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
		name: 'False',
		title: 'False',
		description: 'An output representing false.',
		icon: 'times',
		icon_color: 'red-bleed',
		id: 'false',
		footer: 'This can be used to represent outputs.',
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
		name: 'Pause',
		title: 'Pause',
		description: 'Pause an operation.',
		icon: 'pause',
		icon_color: 'yellow-bleed',
		id: 'pause',
		footer: 'This can be used to represent processes.',
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
		name: 'Play',
		title: 'Play',
		description: 'Continue or start an operation.',
		icon: 'play',
		icon_color: 'green-bleed',
		id: 'play',
		footer: 'This can be used to represent processes.',
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
		name: 'And',
		title: 'And',
		description: 'Check if something is equal to another.',
		icon: 'equals',
		icon_color: 'purple-bleed',
		id: 'and',
		footer: 'This can be used to represent processes.',
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
		name: 'Or',
		title: 'Or',
		description: 'Check if something or another qualifies as true.',
		icon: 'scale-unbalanced',
		icon_color: 'purple-bleed',
		id: 'or',
		footer: 'This can be used to represent processes.',
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
		name: 'Inequal',
		title: 'Inequal',
		description: 'Check if something or another qualifies as true.',
		icon: 'not-equal',
		icon_color: 'purple-bleed',
		id: 'inequal',
		footer: 'This can be used to represent processes.',
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
		name: 'Else',
		title: 'Else',
		description: 'Do something else.',
		icon: 'arrow-left',
		icon_color: 'purple-bleed',
		id: 'else',
		footer: 'This can be used to represent processes.',
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
        name: 'One',
		title: '',
		description: 'Denotes true.',
		icon: '1',
		icon_color: 'purple-bleed',
		id: 'one',
		footer: 'This can be used to represent outputs.',
		class: null,
		editInfo: true,
		category: 'computer',
	},
	{
		name: 'Zero',
		title: '',
		description: 'Denotes false.',
		icon: '0',
		icon_color: 'purple-bleed',
		id: 'zero',
		footer: 'This can be used to represent outputs.',
		class: null,
		editInfo: true,
		category: 'computer',
	},

    // Decision Trees
    {
        name: 'Does',
        title: 'Does',
        description: 'Check if something is equal to another.',
        icon: 'equals',
        icon_color: 'purple-bleed',
        id: 'and',
        footer: 'This can be used to represent processes.',
        class: null,
        editInfo: true,
        category: 'decision',
    },

];